### ISSUE TITLE
Ошибка при сборке на Ubuntu 14.04 x64

### ISSUE THREAD

**Issue by viatoriche** [mad/pidgin-juick-plugin#12]
Версия из git
OS: Ubuntu 14.04 x64

../src/juick.c: At top level:
../src/juick.c:1635:2: warning: implicit declaration of function ‘N_’ [-Wimplicit-function-declaration]
  N_("Juick"),                                          /**< name */
  ^
../src/juick.c:1635:2: error: initializer element is not constant
../src/juick.c:1635:2: error: (near initialization for ‘info.name’)
../src/juick.c:1637:2: error: initializer element is not constant
  N_("Adds some color and button for juick bot."),  /**< summary */
  ^
../src/juick.c:1637:2: error: (near initialization for ‘info.summary’)
../src/juick.c:1638:2: error: initializer element is not constant
  N_("Adds some color and button for juick bot.\n" \
  ^
../src/juick.c:1638:2: error: (near initialization for ‘info.description’)
../src/juick.c: In function ‘init_plugin’:
../src/juick.c:1784:21: warning: assignment makes pointer from integer without a cast [enabled by default]
  plugin->info->name = _(plugin->info->name);
                     ^
../src/juick.c:1785:24: warning: assignment makes pointer from integer without a cast [enabled by default]
  plugin->info->summary = _(plugin->info->summary);
                        ^
../src/juick.c:1786:28: warning: assignment makes pointer from integer without a cast [enabled by default]
  plugin->info->description = _(plugin->info->description);
                            ^
Waf: Leaving directory `/home/viator/data/src/pidgin-juick-plugin/build'
Build failed
 -> task failed (exit status 1): 
    {task 140037872797968: c juick.c -> juick.c.0.o}
['/usr/bin/gcc', '-DHAVE_CONFIG_H', '-Wall', '-Wextra', '-fPIC', '-pthread', '-I/home/viator/data/src/pidgin-juick-plugin/build', '-I/home/viator/data/src/pidgin-juick-plugin', '-I/usr/include/gtk-2.0', '-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include', '-I/usr/include/atk-1.0', '-I/usr/include/cairo', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/pango-1.0', '-I/usr/include/gio-unix-2.0', '-I/usr/include/freetype2', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/pixman-1', '-I/usr/include/libpng12', '-I/usr/include/harfbuzz', '-I/usr/include/pidgin', '-I/usr/include/libpurple', '', '../src/juick.c', '-c', '-o', '', 'src/juick.c.0.o']

**Comment by hlystovov** [comment]
sudo apt-get install intltool
./waf configure && ./waf
