### ISSUE TITLE
Pidgin виснет при U @username

### ISSUE THREAD

**Issue by mad** [mad/pidgin-juick-plugin#4]
<pre>
При U @user на pidgin нагрузка на CPU 100% становится.

Debian Sid, pidgin 2.6.2 juick.so из уже скомпилированных взял.

http://juick.com/344893
</pre>

Мне воспроизвести не удалось (пиджин 2.6.3).

**Comment by hlystovov** [comment]
Мне тоже, пробовал и под винду и под линукс. Помню, был похожий баг, но я его исправил, и все бинарники перекомпилировал и выложил.
