### ISSUE TITLE
Возможно баг с форматированием 

### ISSUE THREAD

**Issue by mad** [mad/pidgin-juick-plugin#5]
<pre>
@Alinaki &lt;j://q?account=someuser@gmail.com/Home&reply=#&body=#352047/7> Я
специально не интересовался, но на всяких livecd встречал особо
лёгкие серверы. Но они специфические драйверы не поддерживают,
только mesa http://juick.com/352047#7 
</pre>

В пост вставляется еще и сам урл хммп ссылки &lt;j://q?account=someuser@gmail.com/Home&reply=#&body=#352047/7&gt;

**Comment by hlystovov** [comment]
Это не баг с форматированием. Как я понимаю, alinaki скопировал вручную из окошка адрес (#352047/7). Надо пользоватся правой кнопкой Insert или в пиджин есть пункт "Вставить как простой текст", или, если уже скопировал, жмешь кнопку "Восстановить форматирование". Так любую ссылку, вставленную в окно ввода, пиджин преобразует.
